library aqmar_motors.globals;

bool isLoggedIn = false;
int userId = 0;
int carAdded = 0;
String userName = "";
String userEmail = "";
String userDocumentId = "";
var userCarDocumentId = [];
var vehicleName = [];
var vehicleCountry = [];
var vehicleDU = [];
var vehicleEngine = [];
var vehicleFT = [];
var vehicleFU = [];
var vehicleIP = [];
var vehicleLP = [];
var vehicleMake = [];
var vehicleType = [];
var vehicleModel = [];
var vehicleSubModel = [];
var vehicleTP = [];
var vehicleTS = [];
var vehicleTC = [];
var vehicleTransmission = [];
var vehicleNote = [];
var vehicleYear = [];
